### ISSUE TITLE
Review render of 2016-2017 posts and fix formatting issues

### ISSUE THREAD

**Issue by stephlocke** [lockedatapublished/blog#2]

**Comment by maelle** [comment]
That one has an issue https://itsalocke.com/blog/shiny-module-design-patterns-pass-module-input-to-other-modules/

![image](https://user-images.githubusercontent.com/8360597/37779088-d3862af0-2deb-11e8-9a47-0a85c706e65c.png)

**Comment by Amymcdougall** [comment]
I have fixed this :)
